@baseUrl = http://localhost:3333

@authToken = {{authenticate.response.body.accessToken}}


GET {{baseUrl}}/orders 
Authorization: Bearer {{authToken}}

###
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Delliv",
    "address": "Av. Sapopemba 1372",
    "status": "pending"
}

###
GET {{baseUrl}}/orders/1f3bf06b-5c53-42f2-99e6-2fb0ff98b2c4
Authorization: Bearer {{authToken}}
###
PATCH {{baseUrl}}/orders/1f3bf06b-5c53-42f2-99e6-2fb0ff98b2c4
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "status": "processing"
}

###
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Adel",
    "email": "adelblande@gmail.com",
    "password": "Adel1234"
}

###
GET {{baseUrl}}/users/adelblande@gmail.com


###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "adelblande@gmail.com",
    "password": "Adel1234"
}
